#!/usr/bin/env python3
"""badusb_gen.py — Generate Flipper Zero BadUSB (Ducky Script) payloads from templates.

Usage examples:
  # Generate a custom troll message payload
  python badusb_gen.py troll --message "Hello from Hackercat 🐾" -o my_troll.txt

  # Generate a sysinfo payload with custom output path
  python badusb_gen.py sysinfo --outpath "C:\\Users\\Public\\info.txt" -o sysinfo.txt

  # List available templates
  python badusb_gen.py --list
"""

import argparse
import sys


TEMPLATES = {
    "troll": {
        "description": "Opens Notepad with a custom message, then locks the screen",
        "params": ["message"],
        "script": lambda p: f"""\
REM Generated by badusb_gen.py — Hackercat-git/Scratchpad
REM Template: troll

DELAY 1000
GUI r
DELAY 400
STRING notepad
ENTER
DELAY 600
STRING {p['message']}
DELAY 200
GUI l
""",
    },
    "sysinfo": {
        "description": "Dumps system info to a file and opens it",
        "params": ["outpath"],
        "script": lambda p: f"""\
REM Generated by badusb_gen.py — Hackercat-git/Scratchpad
REM Template: sysinfo
REM Target: Windows 10/11

DELAY 1000
GUI r
DELAY 400
STRING powershell -WindowStyle Hidden -Command "& {{ $out = '{p['outpath']}'; $lines = @(); $lines += '=== System Info ==='; $lines += (Get-ComputerInfo | Format-List | Out-String); $lines += '=== Network ==='; $lines += (Get-NetIPAddress | Format-Table | Out-String); $lines | Set-Content $out; Start-Process notepad $out }}"
ENTER
""",
    },
    "open_url": {
        "description": "Opens a URL in the default browser",
        "params": ["url"],
        "script": lambda p: f"""\
REM Generated by badusb_gen.py — Hackercat-git/Scratchpad
REM Template: open_url

DELAY 1000
GUI r
DELAY 400
STRING {p['url']}
ENTER
""",
    },
}


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate Flipper BadUSB Ducky Script payloads from templates.")
    parser.add_argument("template", nargs="?", help="Template name")
    parser.add_argument("--list", action="store_true", help="List available templates")
    parser.add_argument("--message", help="[troll] Message to display")
    parser.add_argument("--outpath", default=r"$env:USERPROFILE\Desktop\output.txt", help="[sysinfo] Output file path")
    parser.add_argument("--url", help="[open_url] URL to open")
    parser.add_argument("-o", "--output", default="payload.txt", help="Output .txt file (default: payload.txt)")
    args = parser.parse_args(argv)

    if args.list:
        print(f"{'Template':<12} {'Params':<20} Description")
        print("-" * 60)
        for name, t in TEMPLATES.items():
            print(f"{name:<12} {', '.join(t['params']):<20} {t['description']}")
        return

    if not args.template:
        parser.print_help()
        sys.exit(1)

    if args.template not in TEMPLATES:
        sys.exit(f"Unknown template '{args.template}'. Use --list to see available templates.")

    tmpl = TEMPLATES[args.template]
    params = {"message": args.message, "outpath": args.outpath, "url": args.url}

    missing = [p for p in tmpl["params"] if not params.get(p)]
    if missing:
        sys.exit(f"Template '{args.template}' requires: {', '.join(f'--{p}' for p in missing)}")

    script = tmpl["script"](params)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(script)

    print(f"Written → {args.output}")


if __name__ == "__main__":
    main()
